Adiciona documentação do Lean Inception
fga-eps-mds/2022-2-MeasureSoftGram-Doc pull request #63
Opened 2022-12-13 03:52 UTC by alvesitalo

## Descrição

Adiciona documento com as etapas e tempo gasto nas atividades do Lean Inception
## Está consertando alguma issue aberta?
Closed #47

## Tarefas gerais realizadas
- [ ] Documentar Lean inception
- [ ] Adicionar quadro iterativo
- [ ] Possivelmente documentar horas gastas

2022-12-20 02:05 UTC, Joao-Moura requested changes
Parabéns pelo trabalho galera. Identifiquei alguns errinhos e comentei. Uma coisa que eu senti falta foi o quadro interativo lá do mural. Se possível consigam o iframe para botar nesse doc que vai ficar bem legal.

2022-12-20 02:05 UTC, Joao-Moura commented on docs/plano-monitoramento/visao_de_produto.md
> +## Canvas MVP
Atualizar imagem do canvas

2022-12-20 02:05 UTC, Joao-Moura commented on docs/plano-monitoramento/visao_de_produto.md
> +![Persona 4](assets/persona_Gustavo.png "Persona 4: Estudante de TI")
Atualizar essa persona

2022-12-20 02:05 UTC, Joao-Moura commented on docs/plano-monitoramento/visao_de_produto.md
> +![Jornada 4](assets/jornada_Gustavo.png)
Atualizar essa jornada

2022-12-22 15:42 UTC, alvesitalo commented on docs/plano-monitoramento/visao_de_produto.md
> +- A segunda foi realizada no dia 25/11/22 (17h), via Teams, e durou cerca de 1 hora e 30 minutos.
Adicionado em todos os tópicos

2022-12-22 16:00 UTC, alvesitalo commented
Pronto para revisão novamente 😄

2022-12-25 13:12 UTC, Joao-Moura approved these changes
Parabéns pelo trabalho galera

2022-12-25 13:13 UTC, merged